### ISSUE TITLE
ERROR: No matching distribution found for torch==1.7.0

### ISSUE THREAD

**Issue by clagger** [lemay-ai/lazyTextPredict#43]
Hey folks,

Can anybody help how to install the dependencies to install the lazy-text-precit via pip (or pipenv)?

When I execute the pip install lazy-text-precit command, the cmd line prompts that torch 1.7.0+cu101 is missing.
I have CUDA installed with version 10.1.105 (nvcc -V) but when I want to install pytorch 1.7.0 with cuda with the command:
`# CUDA 10.1
pipenv install torch==1.7.0+cu101 torchvision==0.8.0+cu101 torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html
`
I always get the error: 
_Installing torch==1.7.0...
Error:  An error occurred while installing torch==1.7.0!
Error text:
ERROR: Could not find a version that satisfies the requirement torch==1.7.0 (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch==1.7.0_

Currently I'm using python 3.6 as this is the version used in the google colab notebook,

If anybody can give me a hint this would be awesome!

**Comment by epb378** [comment]
Hi clagger, I haven't seen that issue before, let me look into it! :)

**Comment by clagger** [comment]
Maybe the origin of this error is I'm using pipenv as my python environment?
I'll with a plain python env too and keep you updated!

**Comment by clagger** [comment]
@epb378 So lazy-text-predict needs  Torch 1.70 and Cuda 10.1 installed (torch==1.7.0+cu101)
Using pipenv install and the proper command from PyTorch it will always result in an error.
I finally found the origin - pipenv is causing the error.
Using the following command, you bypass the pipfile and the pipfile.lock integration of torch but install it without errors:
`pipenv run pip install torch==1.7.0+cu101 torchvision==0.8.1+cu101 torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html`

Thank you for creating this package!
